name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, macos-11.0, ubuntu-16.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Start Xvfb
        run: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        if: runner.os == 'Linux'
      - name: Clean Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
        env:
          CI: true
